### ISSUE TITLE
Cannot read property 'scope' of undefined

### ISSUE THREAD

**Issue by sandeepkashyap** [joelwatson/mention-field#2]
_This line:_
"me.doQuery(rawValue, true, true);"

_pops the following error:_
"Cannot read property 'scope' of undefined"

_in the:_
addListener: function(ename, fn, scope, options, order, caller) {
    ....
    ....
    innerScope = config.scope; _// error in this line_
    ....
}

**Comment by joelwatson** [comment]
Thanks for the report--this has been fixed in the 6.0.2 branch.

**Comment by sandeepkashyap** [comment]
Awesome! Thanks :)
