### ISSUE TITLE
Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by sandeepkashyap** [joelwatson/mention-field#3]
onKeyUp: function(e, target) {
    ....
    ....
    me.collapse();
    ....
}

_function pops the following error:_
"Cannot read property 'destroy' of undefined"

_in this //Ext.form.field.Picker function:_
collapse: function() {
    ....
    ....
    me.scrollListeners.destroy();
    ...
}

**Comment by joelwatson** [comment]
Thanks for the report--this has been fixed in the 6.0.2 branch.

**Comment by sandeepkashyap** [comment]
Awesome! Thanks :)
