### ISSUE TITLE
Deselect the selected combo value.

### ISSUE THREAD

**Issue by sandeepkashyap** [joelwatson/mention-field#4]
Once a combo value is selected (mentioned), the value stays selected can not be re-used till the time one doesn't select some another option. 

Requires deselecting the selected value on new mention trigger I believe.

**Comment by joelwatson** [comment]
Thanks for the report! This should be resolved in the latest commits. Thanks!

**Comment by sandeepkashyap** [comment]
Perfect! It worked fine :)
